### ISSUE TITLE
Question: What is counter

### ISSUE THREAD

**Issue by SirDeveloperOrg** [mcraiha/CSharp-ChaCha20-NetStandard#2]
Hi, thanks for your great works, I just want to ask what is counter? Can I use a number like 9999 for counter? higher value higher security?

**Comment by mcraiha** [comment]
Hi, the longer name for it is **block counter**. Using higher number does not make encryption more secure, it just indicates which block is being encrypted. If you want to know why it is there, then I suggest reading 
https://crypto.stackexchange.com/questions/70094/does-chacha20-counter-actually-increment-through-iterations#:~:text=The%20keystream%20is,the%20block%20cipher.)

**Comment by SirDeveloperOrg** [comment]
I really appreciate for your response, actually I don't know much thing about cryptography can you just tell me what number should I use for counter?
Regards.

**Comment by mcraiha** [comment]
Use 0, if you don't have any special reason to change it.

**Comment by SirDeveloperOrg** [comment]
thanks
